In [1]:
import numpy as np
import pandas as pd

In [2]:
df  = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [4]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['W' +str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' +str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [20]:
par = initialize_parameters([2,2,1])
par

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [5]:
def sigmoid(Z):
  A = 1/(1+np.exp(-Z))
  return A

In [6]:
def linear_forword(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  A = sigmoid(Z)
  return A

In [7]:
def L_Layer_forword(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    W1 = parameters['W' +str(l)]
    b1 = parameters['b' +str(l)]
    # print("A" + str(l-1)+": ", A_prev)
    # print("W"+str(l)+": ",W1)
    # print("b"+str(l)+": ",b1)
    # print("--"*20)

    A = linear_forword(A_prev, W1, b1)
    # print("A"+str(l)+": ",A)
    # print("**"*20)

  return A, A_prev

In [42]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * (y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * (y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (y-y_hat)* parameters['W2'][0][0]* A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * (y-y_hat)* parameters['W2'][0][0]* A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * (y-y_hat)* parameters['W2'][0][0]* A1[0][0]*(1-A1[0][0]))

  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (y-y_hat)* parameters['W2'][1][0]* A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (y-y_hat)* parameters['W2'][1][0]* A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * (y-y_hat)* parameters['W2'][1][0]* A1[1][0]*(1-A1[1][0]))

In [43]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['placed']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat, A1 = L_Layer_forword(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss of the students: ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat) )
parameters

Loss of the students:  0.613402628898913


{'W1': array([[0.10005146, 0.10005146],
        [0.10005146, 0.10005146]]),
 'b1': array([[6.43254269e-06],
        [6.43254269e-06]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.00045849]])}

In [44]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['placed']].values[1][0]


y_hat, A1 = L_Layer_forword(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss of the students: ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat) )
parameters

Loss of the students:  0.61289084563907


{'W1': array([[0.10009661, 0.10009661],
        [0.10010951, 0.10010951]]),
 'b1': array([[1.28820601e-05],
        [1.28820601e-05]]),
 'W2': array([[0.10076277],
        [0.10076277]]),
 'b2': array([[0.00091671]])}

In [45]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1)
y = df[['placed']].values[2][0]


y_hat, A1 = L_Layer_forword(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss of the students: ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat) )
parameters

Loss of the students:  0.781016378839329


{'W1': array([[0.10005106, 0.10005106],
        [0.10003359, 0.10003359]]),
 'b1': array([[5.29093302e-06],
        [5.29093302e-06]]),
 'W2': array([[0.10031164],
        [0.10031164]]),
 'b2': array([[0.00037465]])}

In [46]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1)
y = df[['placed']].values[3][0]


y_hat, A1 = L_Layer_forword(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss of the students: ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat) )
parameters

Loss of the students:  0.7817694400219578


{'W1': array([[0.10001571, 0.10001571],
        [0.09994875, 0.09994875]]),
 'b1': array([[-1.77952039e-06],
        [-1.77952039e-06]]),
 'W2': array([[0.09985297],
        [0.09985297]]),
 'b2': array([[-0.00016775]])}

In [47]:
parameters = initialize_parameters([2,2,1])
epochs = 75

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_Layer_forword(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append( -y*np.log(y_hat) - (1-y)*np.log(1-y_hat) )

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.6972698233498175
Epoch -  2 Loss -  0.6972506712235714
Epoch -  3 Loss -  0.69723161495965
Epoch -  4 Loss -  0.6972126540632851
Epoch -  5 Loss -  0.6971937880423278
Epoch -  6 Loss -  0.6971750164072361
Epoch -  7 Loss -  0.6971563386710594
Epoch -  8 Loss -  0.6971377543494248
Epoch -  9 Loss -  0.697119262960523
Epoch -  10 Loss -  0.6971008640250941
Epoch -  11 Loss -  0.6970825570664134
Epoch -  12 Loss -  0.697064341610279
Epoch -  13 Loss -  0.6970462171849962
Epoch -  14 Loss -  0.6970281833213644
Epoch -  15 Loss -  0.6970102395526647
Epoch -  16 Loss -  0.6969923854146447
Epoch -  17 Loss -  0.6969746204455056
Epoch -  18 Loss -  0.6969569441858894
Epoch -  19 Loss -  0.6969393561788646
Epoch -  20 Loss -  0.6969218559699142
Epoch -  21 Loss -  0.6969044431069212
Epoch -  22 Loss -  0.6968871171401566
Epoch -  23 Loss -  0.6968698776222657
Epoch -  24 Loss -  0.6968527241082554
Epoch -  25 Loss -  0.6968356561554817
Epoch -  26 Loss -  0.6968186733236359

{'W1': array([[0.10119811, 0.10119811],
        [0.0964198 , 0.0964198 ]]),
 'b1': array([[-0.00011724],
        [-0.00011724]]),
 'W2': array([[0.08996604],
        [0.08996604]]),
 'b2': array([[-0.01148326]])}

In [33]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Input

In [48]:
model = Sequential()

model.add(Input(shape=(2,)))
model.add(Dense(2, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [49]:
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
model.get_weights()

[array([[ 1.2151812 ,  0.13843894],
        [-1.1291771 , -0.26004148]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0161028],
        [-1.2061423]], dtype=float32),
 array([0.], dtype=float32)]

In [51]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype= np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [52]:
model.set_weights(new_weights)

In [53]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [55]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [56]:
model.fit(df.iloc[:,0:-1].values, df['placed'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 3ms/step - loss: 0.6974
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6969
Epoch 3/75
4/4 [==============================] - 0s 4ms/step - loss: 0.6968
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6968
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6968
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6967
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6965
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6965
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6967
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6964
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6966
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 0.6963
Epoch 13/75
4/4 [==============================] - 0s 3ms/step - loss: 0.